[project]
name = "downstream-builder"
version = "0.1.0"
description = "Utility to assist building downstream artifacts for quipucords-related projects."
requires-python = "<3.14,>=3.12"
authors = [
    {name = "Quipucords Dev Team", email = "quipucords@redhat.com"},
]
readme = "README.md"
# license should preferably follow identifiers listed at the SPDX Open Source License Registry.
# https://spdx.org/licenses/
license = {text = "GPL-3.0-or-later"}
dependencies = [
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
    "rich>=14.0.0",
]

[tool.setuptools]
packages = ["discobuilder"]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]

[build-system]
requires = ["setuptools >= 70"]
build-backend = "setuptools.build_meta"

